### ISSUE TITLE
segmentsBackgroundColor cannot be changed

### ISSUE THREAD

**Issue by roopeshmittal** [twicketapp/TwicketSegmentedControl#12]
Looks like this will never be set to a new value as its always set to background color in setter

```
open var segmentsBackgroundColor: UIColor = Palette.segmentedControlBackgroundColor {
        didSet {
            backgroundView.backgroundColor = backgroundColor
        }
    }
```

**Comment by poolqf** [comment]
Sorry about that issue. This has been fixed in https://github.com/twicketapp/TwicketSegmentedControl/pull/10
