### ISSUE TITLE
func didSelect(_ segmentIndex: Int) Not working for me.

### ISSUE THREAD

**Issue by sashalondon** [twicketapp/TwicketSegmentedControl#3]
Hi great framework you have made. I have installed the TwicketSegmentedControl and used the delegate after the class declaration. I use the func didSelect(_ segmentIndex: Int) but it does not react to changes. Can you update your example with the implementation please?

**Comment by poolqf** [comment]
HI @sashalondon, just updated the example: https://github.com/twicketapp/TwicketSegmentedControl/commit/471d81c2cd3972788f6f5d0863733d821a893ae7

If you have any problem, feel free to reopen the issue

**Comment by sashalondon** [comment]
Thank you.
