### ISSUE TITLE
Segment color when selected get blur

### ISSUE THREAD

**Issue by leminhtuan2015** [twicketapp/TwicketSegmentedControl#7]
![screen shot 2016-10-30 at 1 49 29 pm](https://cloud.githubusercontent.com/assets/4700102/19834943/f915a1e4-9ea7-11e6-9a07-18c62592528d.png)

I dont know why the color near by the selected segment is always blur?

Please point me out how to solve this problem, Thank Sir so much!

**Comment by poolqf** [comment]
It is the expected behaviour. The selected indicator has an halo

**Comment by leminhtuan2015** [comment]
@poolqf  My we have an option to disable the halo?

**Comment by poolqf** [comment]
All right, could be possible

**Comment by leminhtuan2015** [comment]
@poolqf Thank Sir! I am waiting for new function!

**Comment by Manny7311** [comment]
When DidSelect gets called and then call tableView.reloadData(), the data updates in the tableView but the segment stays in [0] although the console prints that [1] was selected. I only have two segments, it's getting called, the tableview is reloading with the correct counts and titles, but the segment stays in place. Please help! Thanks.
