### ISSUE TITLE
DidSelect TableView.reloaddata()

### ISSUE THREAD

**Issue by Manny7311** [twicketapp/TwicketSegmentedControl#8]
Everything is working on DidSelect, but when I call tableview.reload the tableview reloads with the correct data but the segmented control stays on index[0] even though the print says index[1]. I only have two titles on the segementedControl.

When I select index[1] the segment jumps to it and immediately switches back to index[0].

**Comment by poolqf** [comment]
Would help if you post the code that creates/affects the TwicketSegmentedControl
