### ISSUE TITLE
White square around segment control ? 

### ISSUE THREAD

**Issue by fadylateef** [twicketapp/TwicketSegmentedControl#9]
Could I remove or change the white color behind the segment control ? 
Thanks in advance for great library

<img width="282" alt="screen shot 2016-12-13 at 8 23 27 pm" src="https://cloud.githubusercontent.com/assets/17549441/21150958/7d074a5a-c169-11e6-8efb-1aa0d68cc9c1.png">

*UPDATE : I managed to do it by setting segmentedControl.backroundColor to clear color

**Comment by MaeseppTarvo** [comment]
`segmentedControl.backroundColor` not affecting anything. What is the fix for this?
